name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  on-pull-request:
    name: test
    strategy:
      matrix:
        go-version:
          - 1.21.x
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true # caching and restoring go modules and build outputs

      - run: go env

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go--

      - name: go mod tidy
        run: go mod tidy && git diff --exit-code

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61.0
          skip-cache: true  # cache/restore is done by actions/setup-go@v3 step
          args: -v

      - name: Install deps
        run: go mod download

      - name: Test
        run: go test ./...

